# Generated by Django 3.1.2 on 2020-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('referesh_token', models.TextField()),
                ('token_type', models.CharField(max_length=100)),
                ('expires_in', models.BigIntegerField()),
            ],
        ),
    ]
