# Generated by Django 3.1.2 on 2020-10-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cscs_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
