# Generated by Django 3.1.2 on 2020-10-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201023_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trade_account_type',
        ),
    ]
